name: taskcsc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  http: ^1.2.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/font/ClashDisplay-Regular.otf
          weight: 400
        - asset: assets/font/ClashDisplay-Bold.otf
          weight: 700
